"""Alteracao nas tabelas Usuario e Pedido

Revision ID: 959b8be86056
Revises: 2afaf032019a
Create Date: 2025-10-20 19:58:02.538020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959b8be86056'
down_revision: Union[str, Sequence[str], None] = '2afaf032019a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
